services:
  endpoint:
    image: node:18
    user: node
    command: sh -c "tail -f /dev/null"
    container_name: sisgha-endpoint
    restart: always
    working_dir: /code
    depends_on:
      - endpoint-db
    env_file:
      - .env
    ports:
      - 3001:${PORT}
    volumes:
      - .:/code
    networks:
      - sisgha-net

  endpoint-db:
    image: bitnami/postgresql:15
    container_name: sisgha-endpoint-db
    volumes:
      - 'sisgha-endpoint-db-data:/bitnami/postgresql'
    env_file:
      - .db.env
    networks:
      - sisgha-net

networks:
  sisgha-net:

volumes:
  sisgha-endpoint-db-data:
