name: Deploy to production on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into production server and deploy
        uses: appleboy/ssh-action@master
        
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/sisgha/deploy;

            [ ! -d "sisgha-endpoint" ] && git clone ${{ secrets.REPO_URL }} sisgha-endpoint;

            cd sisgha-endpoint;

            make stop-deploy;

            git fetch;
            git reset origin/main --hard;
            
            make start-deploy;